# Generated by Django 5.0.2 on 2024-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='product_files/'),
        ),
    ]
